CC=clang
CFLAGS=-Wall -Wextra -pedantic -O3 -march=native

.PHONY: all clean

all: day18a day18b

day18a: day18a.c
	$(CC) $(CFLAGS) -o day18a day18a.c

day18b: day18b.c
	$(CC) $(CFLAGS) -o day18b day18b.c

clean:
	rm -vf day17
